import React from 'react'
import {
  MdMenu,
  MdHub,
  MdClose,
  MdDashboard,
  MdGroup,
  MdWork,
  MdAssignmentTurnedIn,
  MdAssignment,
  MdPayments,
  MdMail,
  MdRateReview,
  MdBarChart,
  MdSettings,
  MdLogout,
  MdSearch,
  MdNotifications,
  MdHelpOutline,
  MdCalendarToday,
  MdExpandMore,
  MdMoreVert,
  MdStar,
  MdChevronLeft,
  MdChevronRight,
  MdDescription,
  MdDownload,
  MdTrendingUp,
  MdTrendingDown,
  MdAdd,
  MdAddCircle,
  MdTune,
  MdMoreHoriz,
  MdPersonAdd,
  MdReport,
  MdDelete,
  MdDoneAll,
  MdChat,
  MdDrafts,
  MdLock,
  MdVisibility,
  MdVisibilityOff,
  MdLogin,
  MdBolt,
  MdAutorenew,
} from 'react-icons/md'

const iconMap: Record<string, React.ComponentType<{ className?: string; size?: number; color?: string }>> = {
  menu: MdMenu,
  hub: MdHub,
  close: MdClose,
  dashboard: MdDashboard,
  group: MdGroup,
  work: MdWork,
  assignment_turned_in: MdAssignmentTurnedIn,
  assignment: MdAssignment,
  payments: MdPayments,
  mail: MdMail,
  reviews: MdRateReview,
  bar_chart: MdBarChart,
  settings: MdSettings,
  logout: MdLogout,
  search: MdSearch,
  notifications: MdNotifications,
  help_outline: MdHelpOutline,
  calendar_today: MdCalendarToday,
  expand_more: MdExpandMore,
  more_vert: MdMoreVert,
  more_horiz: MdMoreHoriz,
  star: MdStar,
  chevron_left: MdChevronLeft,
  chevron_right: MdChevronRight,
  description: MdDescription,
  download: MdDownload,
  trending_up: MdTrendingUp,
  trending_down: MdTrendingDown,
  add: MdAdd,
  add_circle: MdAddCircle,
  tune: MdTune,
  person_add: MdPersonAdd,
  report: MdReport,
  delete: MdDelete,
  done_all: MdDoneAll,
  chat: MdChat,
  drafts: MdDrafts,
  lock: MdLock,
  visibility: MdVisibility,
  visibility_off: MdVisibilityOff,
  login: MdLogin,
  bolt: MdBolt,
  progress_activity: MdAutorenew,
}

export default function Icon({ name, className, size, color }: { name: string; className?: string; size?: number; color?: string }) {
  const Comp = iconMap[name]
  if (!Comp) return null
  return <Comp className={className} size={size} color={color} />
}
