import express from 'express';
import { authenticate } from '../core/middleware/auth.middleware.js';
import * as CollaboController from '../controllers/Collabo.controller.js';
import { upload } from '../core/utils/fileUpload.js';
const router = express.Router();
router.post('/create', authenticate, CollaboController.createCollaboProject);
router.post('/scope', authenticate, CollaboController.scopeProject);
router.get('/my-projects', authenticate, CollaboController.getMyProjects);
router.get('/freelancer-projects', authenticate, CollaboController.getFreelancerProjects);
router.post('/accept-role', authenticate, CollaboController.acceptRole);
router.post('/message', authenticate, CollaboController.sendMessage);
router.post('/mark-read', authenticate, CollaboController.markRead);
router.get('/messages', authenticate, CollaboController.getMessages);
router.post('/task', authenticate, CollaboController.createTask);
router.get('/tasks', authenticate, CollaboController.getTasks);
router.patch('/task/:id', authenticate, CollaboController.updateTask);
router.delete('/task/:id', authenticate, CollaboController.deleteTask);
// Files (must be before /:id route)
router.post('/file', authenticate, upload.single('file'), CollaboController.uploadFile);
router.get('/files', authenticate, CollaboController.getFiles);
router.delete('/file/:id', authenticate, CollaboController.deleteFile);
router.get('/activities', authenticate, CollaboController.getActivities);
router.post('/:id/fund', authenticate, CollaboController.fundProject);
router.post('/:id/fund-wallet', authenticate, CollaboController.fundProjectFromWallet);
router.post('/:id/activate', authenticate, CollaboController.activateProject);
router.post('/:id/start', authenticate, CollaboController.startWork);
router.patch('/role/:roleId', authenticate, CollaboController.updateRole);
router.post('/:id/auto-tasks', authenticate, CollaboController.generateAutoTasks);
router.post('/role/:roleId/remove', authenticate, CollaboController.removeFromRole);
router.post('/role/:roleId/invite', authenticate, CollaboController.inviteToRole);
router.post('/role/:roleId/ai-invite', authenticate, CollaboController.aiInviteToRole);
router.post('/:id/role', authenticate, CollaboController.addRole);
router.get('/:id', authenticate, CollaboController.getCollaboProject);
router.get('/role/:id', authenticate, CollaboController.getRole);
export default router;
